packages:
<<<<<<< HEAD
  - package/*
  - playground/*

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild
  - sharp
=======
  - koukoku
  - tamesu
  - uragawa

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
  - workerd
>>>>>>> koukokuv/main
